php_version: '7.1'
php_use_managed_ini: false
php_packages:
  - php
  - php-cli
  - php-common
  - php-opcache
  - php-gd
  - php-mysqlnd
  - php-mbstring
  - php-xml
  - php-tidy
  - php-soap
  - php-pear
  - php-pecl-xdebug
  - php-bcmath
  - php-devel
  - php-apc
php_display_errors: "On"
