---
- name: My first playbook :)
  hosts: "databases"
  become: true
  become_user: root
  vars:
    server_name: localhostNode
    cache_size: 10GB
  tasks:
    - name: capture output of whoami command
      command: whoami
      register: login

    - name: debug
      debug: var=login

    - name: Install Apache
      yum: pkg=httpd state=present

    - name: Add configuraction file in Apache conf.d
      copy: src=files/configuration.conf dest=/etc/httpd/conf.d/configuration.conf

    - name: Create default HTML with SO version
      template: src=templates/index.html dest=/home/vagrant/index_new.html

    - name: restart Apache
      service: name=httpd state=restarted