---
- name: My first playbook :)
  hosts: "databases"
  become: true
  become_user: root
  vars:
    server_name: localhostNode
    cache_size: 10GB
  tasks:
    - name: "Show message if distribution is Debian"
      debug: msg="Is Debian!"
      when: ansible_os_family == "Debian"

    - name: "Show message if distribution is RedHat"
      debug: msg="Is RedHat!"
      when: ansible_os_family == "RedHat"
  roles:
    - apache